# conf_generator.py
# -*- coding: utf-8 -*-
# @Author: sidmishraw
# @Date:   2017-05-18 14:19:59
# @Last Modified by:   sidmishraw
# @Last Modified time: 2017-05-18 14:45:21


"""
Gives you the number of words in the document set by parsing the word_map.json document.
Then, it prints the number of documents in the document set by parsing the doc_map.json document.
The doc_map.json and word_map.json are generated by the SimplicalComplexDataCreator application
when it generates the s_output.data and sorted s_output.dat files.
"""

from json import loads
from json import dumps
from chardet import detect


if __name__ == '__main__':

  print("""
    _____------------ Configuration generator --------______
    Please find the recommended configuration for max row/col counts below:
    """)
  print('')

  with open('word_map.json', 'rb') as fopen:
    s = fopen.read()
    encoding = detect(s)['encoding']
    print('Encoding detected for word_map = ', encoding)
    d = loads(str(s, encoding=encoding))
    print("max_number_words = ", len(d))
    print('Please use this as your max column count')

  print('')
  print('')

  with open('doc_map.json', 'rb') as fopen:
    s = fopen.read()
    encoding = detect(s)['encoding']
    print('Encoding detected for doc_map = ', encoding)
    d = loads(str(s, encoding=encoding))
    print("max_number_docs = ", len(d))
    print('Please use this as your max row count')

  print('')
  print('')
